name: GenuineMMO
author: kainianer
webseite: http://www.kainaner.com
version: 1.0 Alpha
main: de.kainianer.mmo.main.Main
depend: [WorldGuard]
commands:
    test:
        description: test
    group:
        description: Functionality of a group.